server:
  port: 8081

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5433/airbnb
    username: airbnb
    password: airbnb_secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: notification
    open-in-view: false

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

  jms:
    listener:
      session-transacted: true
      auto-startup: true
      concurrency: 3

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    notification: DEBUG
    org.springframework.jms: DEBUG